server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ehree_server?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    password: hxl.123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

