spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # 格式化SQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true

ehree:
  api-basepackage: com.hxl.api

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
