spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # 格式化SQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    # 控制序列化的下划线
    property-naming-strategy: SNAKE_CASE
    serialization:
      # 控制时间序列化的时间戳
      WRITE_DATES_AS_TIMESTAMPS: true

ehree:
  api-basepackage: com.hxl.api
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
